model:
    name: histo-ai
    filename: models/model-best.h5
    description: model-best.h5
    id: 1
    version: 1
    type: image
    framework: keras
    inputs:
        - type: str
          value: image
    outputs:
        - type: int
          value: is_cancer
    labels: 
    preprocessing:
        rgb: true
        scale: false
